services:
  atlas-life:
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: .
    container_name: ${APP_NAME}_${APP_VERSION}
    ports:
      - "${APP_PORT}:8501"
    volumes:
      - ./db/Beta:/app/db/Beta
      - ./key:/app/key:ro
    env_file:
      - .env
    restart: unless-stopped
